const express = require('express');
const router = express.Router();
const categoryController = require('../controllers/categoryController');
const verifyToken = require('../middlewares/verifyToken');
const isAdmin = require('../middlewares/isAdmin');
router.post('/', verifyToken,isAdmin,categoryController.createCategory);
router.get('/', categoryController.getAllCategories);
router.put('/:id', verifyToken,isAdmin,categoryController.updateCategory);
router.delete('/:id', verifyToken,isAdmin,categoryController.deleteCategory);
router.get('/:slug', categoryController.getCategoryBySlug);
router.get('/shop/:shopId', categoryController.getCategoriesForShop);
router.get('/shops/:slug', categoryController.getShopsByCategory);
module.exports = router;
